exclude: "node_modules|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        files: '^github_connector/.*\.py'
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        files: '^github_connector/.*\.py'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        files: '^github_connector/.*\.py'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              github_connector/public/dist/.*|
              .*node_modules.*|
              .*boilerplate.*|
              github_connector/www/website_script.js|
              github_connector/templates/includes/.*|
              github_connector/public/js/lib/.*|
              github_connector/website/doctype/website_theme/website_theme_template.scss
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ["--quiet"]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              github_connector/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*|
              github_connector/www/website_script.js|
              github_connector/templates/includes/.*|
              github_connector/public/js/lib/.*
          )$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: '^github_connector/.*\.py'

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-isort", "flake8-bugbear"]
