name: Semantic Commits

on:
  pull_request:

jobs:
  commitlint:
    name: Semantic Commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install commitlint
        run: npm install --no-save @commitlint/cli @commitlint/config-conventional

      - name: Check commit titles
        run: >-
          npx commitlint --verbose
          --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }}
